### ISSUE TITLE
Respect the AWS_PROFILE environment variable

### ISSUE THREAD

**Issue by ww-daniel-mora** [technogise/dynamo-data-migrations#24]
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html#cli-configure-files-using-profiles

AWS tools use the `AWS_PROFILE` environment variable if set to determine which profile to use. This CLI should respect that variable if it is set.

**Comment by ww-daniel-mora** [comment]
Addressed in #23

**Comment by mukund1488** [comment]
> Addressed in #23

Version 4.1.4 released with above changes.

**Comment by ww-daniel-mora** [comment]
Thank you @mukund1488
